insert into usuario values(2,'Panaderia Industrial','Pan delicioso caliente mañana y tarde','7ma. Avenida 7-99 Zona 2 San Pedro Sacatepequez San  Marcos','Surgio el 19  de abril  de 1991,  por la iniciativa de  Victor Manuel Bautista, con el  apoyo de su esposa Floridalma Yolanda Miranda  De Bautista, a  ocho dias del nacimiento  de sus hijos gemelos, ya que por el embarazo se le dificultaba caminar y los él bienestar  de los tres hijos menores  de siete años, empezaron la elaboración  del pan en su casa de habitación ubicada en 7ave. 7-99 callejón 3 zona 2 del municipio de San Pedro Sacatepéquez, departamento  de San Marcos y donde actualmente  se encuentra, pero por falta de recurso económico no se contó con un local para distribución de pan lo que desde la fecha  se ha vendido en el portón del centro comercial número 1  de nuestro municipio, y otras comunidades como San Sebastián, palestina, Sibilia, Rio Blanco, y el tumbador San Marcos.
Para la elaboración de pan se contaba con horno con mesa de adobe y ladrillos, el cual sufrió daños considerables por el terremoto del año 2012, por lo que fue necesario la construcción  de uno nuevo que hasta la fecha sigue funcionando para la elaboracion del pan. 
       Con la ayuda  de  sus 6 hijos han logrado sacar adelante convirtiéndose en un negocio familiar que ha servido para el sustento diario y para la preparación académica   de cada uno de ellos.
Panaderia industrial, con treinta años sirviendo a la población  en general, con las tradicionales shecas sampedranas.
Por la pandemia COVID 19 las ventas han bajado considerablemente   ya que no se cuenta con un lugar estable donde vender, por  lo que es importante contar con el apoyo de las instituciones o grupos organizados para seguir con las tradiciones de nuestro querido municipio. ','http://localhost:3000/sources/logoPanaderiaIndustrial.jpg',77608604,'Victor Manuel Bautista',now(),'http://localhost:3000/sources/panaderiaindustrial.jpg',now(),now());
insert into usuario values(3,'Panaderia Industrial','Pan delicioso caliente mañana y tarde','7ma. Avenida 7-99 Zona 2 San Pedro Sacatepequez San  Marcos','Surgio el 19  de abril  de 1991,  por la iniciativa de  Victor Manuel Bautista, con el  apoyo de su esposa Floridalma Yolanda Miranda  De Bautista, a  ocho dias del nacimiento  de sus hijos gemelos, ya que por el embarazo se le dificultaba caminar y los él bienestar  de los tres hijos menores  de siete años, empezaron la elaboración  del pan en su casa de habitación ubicada en 7ave. 7-99 callejón 3 zona 2 del municipio de San Pedro Sacatepéquez, departamento  de San Marcos y donde actualmente  se encuentra, pero por falta de recurso económico no se contó con un local para distribución de pan lo que desde la fecha  se ha vendido en el portón del centro comercial número 1  de nuestro municipio, y otras comunidades como San Sebastián, palestina, Sibilia, Rio Blanco, y el tumbador San Marcos.
Para la elaboración de pan se contaba con horno con mesa de adobe y ladrillos, el cual sufrió daños considerables por el terremoto del año 2012, por lo que fue necesario la construcción  de uno nuevo que hasta la fecha sigue funcionando para la elaboracion del pan. 
       Con la ayuda  de  sus 6 hijos han logrado sacar adelante convirtiéndose en un negocio familiar que ha servido para el sustento diario y para la preparación académica   de cada uno de ellos.
Panaderia industrial, con treinta años sirviendo a la población  en general, con las tradicionales shecas sampedranas.
Por la pandemia COVID 19 las ventas han bajado considerablemente   ya que no se cuenta con un lugar estable donde vender, por  lo que es importante contar con el apoyo de las instituciones o grupos organizados para seguir con las tradiciones de nuestro querido municipio. ','http://localhost:3000/sources/logoPanaderiaIndustrial.jpg',77608604,'Victor Manuel Bautista',now(),'http://localhost:3000/sources/panaderiaindustrial.jpg',now(),now());
insert into usuario values(4,'Panaderia Industrial','Pan delicioso caliente mañana y tarde','7ma. Avenida 7-99 Zona 2 San Pedro Sacatepequez San  Marcos','Surgio el 19  de abril  de 1991,  por la iniciativa de  Victor Manuel Bautista, con el  apoyo de su esposa Floridalma Yolanda Miranda  De Bautista, a  ocho dias del nacimiento  de sus hijos gemelos, ya que por el embarazo se le dificultaba caminar y los él bienestar  de los tres hijos menores  de siete años, empezaron la elaboración  del pan en su casa de habitación ubicada en 7ave. 7-99 callejón 3 zona 2 del municipio de San Pedro Sacatepéquez, departamento  de San Marcos y donde actualmente  se encuentra, pero por falta de recurso económico no se contó con un local para distribución de pan lo que desde la fecha  se ha vendido en el portón del centro comercial número 1  de nuestro municipio, y otras comunidades como San Sebastián, palestina, Sibilia, Rio Blanco, y el tumbador San Marcos.
Para la elaboración de pan se contaba con horno con mesa de adobe y ladrillos, el cual sufrió daños considerables por el terremoto del año 2012, por lo que fue necesario la construcción  de uno nuevo que hasta la fecha sigue funcionando para la elaboracion del pan. 
       Con la ayuda  de  sus 6 hijos han logrado sacar adelante convirtiéndose en un negocio familiar que ha servido para el sustento diario y para la preparación académica   de cada uno de ellos.
Panaderia industrial, con treinta años sirviendo a la población  en general, con las tradicionales shecas sampedranas.
Por la pandemia COVID 19 las ventas han bajado considerablemente   ya que no se cuenta con un lugar estable donde vender, por  lo que es importante contar con el apoyo de las instituciones o grupos organizados para seguir con las tradiciones de nuestro querido municipio. ','http://localhost:3000/sources/logoPanaderiaIndustrial.jpg',77608604,'Victor Manuel Bautista',now(),'http://localhost:3000/sources/panaderiaindustrial.jpg',now(),now());